# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.to_jit": "00_jit.ipynb"}

modules = ["jit.py"]

doc_url = "https://muellerzr.github.io/fastexport/"

git_url = "https://github.com/muellerzr/fastexport/tree/master/"

def custom_doc_links(name): return None
