# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TensorBase.requires_grad_": "00_jit.ipynb",
         "Learner.to_jit": "00_jit.ipynb",
         "Learner.to_fastai": "01_export.ipynb",
         "Learner.export": "01_export.ipynb"}

modules = ["jit.py",
           "export.py"]

doc_url = "https://muellerzr.github.io/fastexport/"

git_url = "https://github.com/muellerzr/fastexport/tree/master/"

def custom_doc_links(name): return None
